### ISSUE TITLE
Exception occurred: No module named 'lvdm' when executing `dynamicrafter_looping_example_01.json`

### ISSUE THREAD

**Issue by timacro** [kijai/ComfyUI-DynamiCrafterWrapper#23]
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> got prompt
> !!! Exception during processing !!!
> Traceback (most recent call last):
>   File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 82, in loadmodel
>     self.model = instantiate_from_config(model_config)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 33, in instantiate_from_config
>     return get_obj_from_str(config["target"])(**config.get("params", dict()))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 42, in get_obj_from_str
>     return getattr(importlib.import_module(module, package=package_directory_name), cls)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "importlib\__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'lvdm'

I try to install https://github.com/YingqingHe/LVDM but it didn't work.

Prompt executed in 0.02 seconds

**Comment by zdyshine** [comment]
Hi, has the problem been resolved?

**Comment by kijai** [comment]
Which model are you trying to load for that error? I did find a bug that would cause this if trying to load the normal 512 model, that's now fixed. Otherwise I can't reproduce that error.

**Comment by zdyshine** [comment]
Thanks for your reply. DynamiCrafter512_model.ckpt will cause the error.  DynamiCrafter1024_model.ckpt is correct, but the result is very poor.

**Comment by kijai** [comment]
> Thanks for your reply. DynamiCrafter512_model.ckpt will cause the error. DynamiCrafter1024_model.ckpt is correct, but the result is very poor.

Ok well that should be fixed now, 512 model should load.

**Comment by zdyshine** [comment]
Great~~~
