### ISSUE TITLE
AttributeError: module 'comfy.sd' has no attribute 'CLIPType'

### ISSUE THREAD

**Issue by FanfannnnChen** [kijai/ComfyUI-DynamiCrafterWrapper#48]
Kijai,
Thanks your contribution.

I'm trying the latest version of [dynamicrafter_i2v_example_01.json] example. I got some clip error.

model checkpoint loaded.
Model using dtype: torch.float16
Loading model from: /home/my_wsl/ComfyUI/models/clip_vision/CLIP-ViT-H-fp16.safetensors
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/my_wsl/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/my_wsl/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/my_wsl/ComfyUI/custom_nodes/ComfyUI-0246/utils.py", line 363, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "/home/my_wsl/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/my_wsl/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/nodes.py", line 164, in loadmodel
    clip_type = comfy.sd.CLIPType.STABLE_DIFFUSION
AttributeError: module 'comfy.sd' has no attribute 'CLIPType'

**Comment by kijai** [comment]
That error would suggest you need to update ComfyUI itself.
