### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'to' when using DynamicCraftBatchProcessor 

### ISSUE THREAD

**Issue by SSA4** [kijai/ComfyUI-DynamiCrafterWrapper#62]
Hi,

everytime I try to use the DynamicCraftBatchProcessor with the "dynamicrafter_512_interp_v1_bf16.safetensors" model I get this error:

Prompt executed in 8.15 seconds
got prompt
VAE using dtype: torch.bfloat16
!!! Exception during processing!!! 'NoneType' object has no attribute 'to'
Traceback (most recent call last):
  File "C:\Stable Diffusion\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stable Diffusion\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stable Diffusion\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Stable Diffusion\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 863, in process
    self.model.cond_stage_model.to(device)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'

Prompt executed in 1.77 seconds

That is is my Comfy workflow:

![error](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/34798862/fb596dfc-8230-4651-9de8-c5b1db1e7946)

**Comment by brad12d3** [comment]
I'm having the exact same issue, did you find a fix? The regular image to video workflow works great but when I decided to try the Interpolation workflow I get the same error you're getting.
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/35470635/513e53be-680f-41bd-880f-2699fdfddb88)
