### ISSUE TITLE
cannot unpack non-iterable DiagonalGaussianDistribution object

### ISSUE THREAD

**Issue by BayJ233** [kijai/ComfyUI-DynamiCrafterWrapper#78]
Error occurred when executing ToonCrafterInterpolation:
cannot unpack non-iterable DiagonalGaussianDistribution object

**Comment by kaelem1** [comment]
same error

**Comment by kijai** [comment]
Need to see the full error, my guess is that pytorch-lighting version isn't compatible.

**Comment by ai-is-in-wonderland** [comment]
same error

!!! Exception during processing!!! cannot unpack non-iterable DiagonalGaussianDistribution object
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 599, in process
    z, hs = get_latent_z_with_hidden_states(self.model, videos)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\scripts\evaluation\funcs.py", line 73, in get_latent_z_with_hidden_states
    encoder_posterior, hidden_states = model.first_stage_model.encode(x, return_hidden_states=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable DiagonalGaussianDistribution object

**Comment by kijai** [comment]
Still no idea what could cause that, just tested with a fresh install on ComfyUI portable and everything works. So it's probably some other node pack installing some other version of one of the dependencies.

**Comment by kijai** [comment]
Oh I know now... you are trying to use non-Tooncrafter model with the ToonCrafter -node?
