### ISSUE TITLE
error after pulling the latest update 

### ISSUE THREAD

**Issue by kotaxyz** [kijai/ComfyUI-DynamiCrafterWrapper#96]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
Loading model from: I:\ComfyUI\ComfyUI\models\checkpoints\dynamicrafter\tooncrafter_512_interp-pruned-fp16.safetensors
LatentVisualDiffusion: Running in v-prediction mode
!!! Exception during processing!!! type object 'manual_cast' has no attribute 'Conv1d'
Traceback (most recent call last):
  File "I:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "I:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "I:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 133, in loadmodel
    self.model = instantiate_from_config(model_config)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 33, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 719, in __init__
    super().__init__(*args, **kwargs)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 399, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 85, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 735, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 33, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\modules\networks\openaimodel3d.py", line 398, in __init__
    TemporalTransformer(
  File "I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\modules\attention.py", line 334, in __init__
    self.proj_in = ops.Conv1d(in_channels, inner_dim, kernel_size=1, stride=1, padding=0)
AttributeError: type object 'manual_cast' has no attribute 'Conv1d'. Did you mean: 'Conv2d'?

Prompt executed in 2.08 seconds

**Comment by kotaxyz** [comment]
@kijai

**Comment by kijai** [comment]
When did you last update your ComfyUI itself?

**Comment by kotaxyz** [comment]
it was it , thanks alot
